apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-argo-application
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/alexweisen/mydevlab.git
    targetRevision: HEAD
    path: mydevlab/k8s-proj/les-01-argocd
  destination: 
    server: https://kubernetes.default.svc
    namespace: lesson-01

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
